name: mazey-npm-template

version: "3.9"

services:
  webpack-dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: webpack-dev:latest
    container_name: webpack-dev
    ports:
      - "8080:8080"
    volumes:
      - ./src:/web/src
      - ./examples:/web/examples
      - ./test:/web/test
      - ./lib:/web/lib
